global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:8081']

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:8082']
